### ISSUE TITLE
audit report failed to be generated

### ISSUE THREAD

**Issue by NancyChunlan** [OSSIndex/ossindex-gradle-plugin#28]
After add following configurations into build.gradle.
Still no audit report generated.
    audit {
        failOnError = false
        junitReport = "./ossindex/junitReport.xml"
    }

Used the latest released version 0.3.20-beta, is it a bug or something wrong with my configuration?
I executed 'gradle audit' to do the audit.
Any comments on this? Thanks!

**Comment by ken-duck** [comment]
Oh dear. Sorry, I missed this message. I will look into it now.

**Comment by ken-duck** [comment]
I agree. There does seem to be a problem. It *ALWAYS" has the name junitReport.xml and does not seem to listen to the path part of the argument. I am working on a fix now.

Sorry for the inconvenience.

**Comment by ken-duck** [comment]
There were two problems that I found:

1. The directory was not being created automatically
2. The error messages were not prominent and were not even being displayed in some cases.

Fixed by commit https://github.com/OSSIndex/ossindex-gradle-plugin/commit/f5fe0148455d39860d7eba21163ce09543ddb247

A new version of the plugin has been published (0.3.21)

**Comment by ken-duck** [comment]
That's great news.

FYI, we are working on a new release which supports the new OSS Index REST v3 API. This means more vulnerabilities, and the v3 database is being actively maintained. There are still some kinks to work out, but once we are out of beta it will be worth upgrading.
