### ISSUE TITLE
Audit task error trying to get audit results

### ISSUE THREAD

**Issue by viniciusrdacosta** [OSSIndex/ossindex-gradle-plugin#6]
Hello, 
I'm trying to use `gradle.plugin.net.ossindex:ossindex-gradle-plugin:0.1.1` with gradle 3.5 but I'm getting a weird error.

![screen shot 2017-05-15 at 18 31 31](https://cloud.githubusercontent.com/assets/1073869/26080398/c7c2fd40-399c-11e7-9d1c-228ca6f99c92.png)

Is it a bug or I'm doing something wrong ?

**Comment by OSSIndex-Admin** [comment]
Thanks for the report. It looks to be a bug. We just had a similar bug come in for the maven plugin with a touch of more information -- it has the looks of a server bug. I will attempt to do a fix tonight,

**Comment by OSSIndex-Admin** [comment]
A server issue has been fixed which was caused by an incorrectly formated version range causing the parser to die in an inglorious way. We manage the exception gracefully, but still need to fix the underlying incorrect version ranges in some vulnerabilities (https://github.com/OSSIndex/website/issues/12)
